openapi: 3.1.0
info:
  version: 1.0.0
  title: <назва вашого додатку>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    <опис вашого додатку>
tags:
  - name: Products
    description: Operations about users
servers:
  - url: http://localhost:3000
  - url: https://goit-node-blended-02.onrender.com
paths:
  /products:
    get:
      $ref: '../swagger/paths/products/get.yaml'
    post:
      $ref: '../swagger/paths/products/post.yaml'
  /products/productId:
    get:
      $ref: '../swagger/paths/products/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/products/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/products/{id}/delete.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auths/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auths/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auths/refresh.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auths/logout.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
